# Generated by Django 4.0.5 on 2022-06-22 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='Nombre del curso')),
                ('short_course_name', models.CharField(max_length=20, verbose_name='Nombre corto del curso')),
                ('course_description', models.TextField(verbose_name='Descripción del curso')),
                ('is_active', models.BooleanField(default=True, help_text='Designa si el curso está activo', verbose_name='Es un curso activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del curso', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición del curso', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'apps_journal_groups_courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_topic_name', models.CharField(max_length=100, verbose_name='Nombre del tema')),
                ('course_topic_description', models.TextField(verbose_name='Descripción del tema')),
                ('viewed_topic', models.BooleanField(default=False, verbose_name='¿Ya se visualizó el tema?')),
                ('view_date_topic', models.DateTimeField(verbose_name='Fecha de visualización del tema')),
                ('is_active', models.BooleanField(default=True, help_text='Designa si el tema está activo', verbose_name='Es un tema activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del tema', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición del tema', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'apps_journal_groups_coursetopics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(error_messages={'requerido': 'Debe ingresar un nombre de grupo', 'único': 'Este nombre de grupo ya existe'}, help_text='Requerido. 150 carácteres o menos', max_length=150, unique=True, verbose_name='Nombre del grupo')),
                ('is_active', models.BooleanField(default=True, help_text='Designa si el grupo está activo', verbose_name='Es un grupo activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del grupo', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición del grupo', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('courses', models.ManyToManyField(to='groups.coursesmodel', verbose_name='Cursos del grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'apps_journal_groups_groups',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.coursetopicsmodel', verbose_name='Tema del curso'),
        ),
    ]
