# Generated by Django 4.0.5 on 2022-06-20 18:18

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIndexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Contenido de la página principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activa?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Contenido principal',
                'verbose_name_plural': 'Contenido principal',
                'db_table': 'apps_home_content_index',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('logo_light', models.ImageField(upload_to='general/logo/light', verbose_name='Logo modo luz')),
                ('logo_dark', models.ImageField(upload_to='general/logo/dark', verbose_name='Logo modo oscuro')),
                ('favicon', models.ImageField(upload_to='general/favicon', verbose_name='Favicon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Se va a mostrar este logo?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Logos',
                'verbose_name_plural': 'Logos',
                'db_table': 'apps_home_logos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StartDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Título del inicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Título del inicio',
                'verbose_name_plural': 'Título del inicio',
                'db_table': 'apps_home_title_index',
                'ordering': ['order'],
            },
        ),
    ]
