# Generated by Django 4.0.5 on 2022-07-13 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro del diario')),
                ('pedagogical_reflection', models.TextField(blank=True, null=True, verbose_name='Reflexión pedagógica')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Designa si el tema está activo', verbose_name='Es un tema activo')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del tema', verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de edición del tema', verbose_name='Fecha de edición')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.coursesmodel', verbose_name='Materia (Ejm: Matemáticas)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.groupsmodel', verbose_name='Grupo (Ejm: 10A)')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.peoplemodel', verbose_name='Profesor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.coursetopicsmodel', verbose_name='Tema del curso (Ejm: Trigonometría)')),
            ],
        ),
    ]
