# Generated by Django 4.0.5 on 2022-06-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designa si el usuario está activo', verbose_name='Es un usuario activo'),
        ),
    ]
